// TypeScript types mirroring mavkit serde output.
// These must match the exact JSON shapes produced by serde serialization
// of the Rust types in mavkit (externally-tagged enums, struct field names).

// ---------------------------------------------------------------------------
// Geo types
// ---------------------------------------------------------------------------

export type GeoPoint2d = {
  latitude_deg: number;
  longitude_deg: number;
};

export type GeoPoint3dMsl = {
  latitude_deg: number;
  longitude_deg: number;
  altitude_msl_m: number;
};

export type GeoPoint3dRelHome = {
  latitude_deg: number;
  longitude_deg: number;
  relative_alt_m: number;
};

export type GeoPoint3dTerrain = {
  latitude_deg: number;
  longitude_deg: number;
  altitude_terrain_m: number;
};

// Externally-tagged enum (no rename_all on the Rust side).
export type GeoPoint3d =
  | { Msl: GeoPoint3dMsl }
  | { RelHome: GeoPoint3dRelHome }
  | { Terrain: GeoPoint3dTerrain };

// ---------------------------------------------------------------------------
// Small enums used as fields inside commands
// ---------------------------------------------------------------------------

export type LoiterDirection = "Clockwise" | "CounterClockwise";
export type AltChangeAction = "Neutral" | "Climb" | "Descend";
export type SpeedType = "Airspeed" | "Groundspeed";
export type FenceAction = "Disable" | "Enable" | "DisableFloor";
export type ParachuteAction = "Disable" | "Enable" | "Release";
export type GripperAction = "Release" | "Grab";
export type WinchAction = "Relax" | "LengthControl" | "RateControl";
export type YawDirection = "Clockwise" | "CounterClockwise";

// ---------------------------------------------------------------------------
// MissionFrame (commands module — not the mission-item frame)
// ---------------------------------------------------------------------------

export type MissionFrame =
  | "Global"
  | "GlobalRelativeAlt"
  | "GlobalTerrainAlt"
  | "Mission"
  | { Other: number };

// ---------------------------------------------------------------------------
// Raw mission command
// ---------------------------------------------------------------------------

export type RawMissionCommand = {
  command: number;
  frame: MissionFrame;
  param1: number;
  param2: number;
  param3: number;
  param4: number;
  x: number;
  y: number;
  z: number;
};

// ---------------------------------------------------------------------------
// Nav command structs
// ---------------------------------------------------------------------------

export type NavWaypoint = {
  position: GeoPoint3d;
  hold_time_s: number;
  acceptance_radius_m: number;
  pass_radius_m: number;
  yaw_deg: number;
};

export type NavSplineWaypoint = {
  position: GeoPoint3d;
  hold_time_s: number;
};

export type NavArcWaypoint = {
  position: GeoPoint3d;
  arc_angle_deg: number;
  direction: LoiterDirection;
};

export type NavTakeoff = {
  position: GeoPoint3d;
  pitch_deg: number;
};

export type NavLand = {
  position: GeoPoint3d;
  abort_alt_m: number;
};

export type NavLoiterUnlimited = {
  position: GeoPoint3d;
  radius_m: number;
  direction: LoiterDirection;
};

export type NavLoiterTurns = {
  position: GeoPoint3d;
  turns: number;
  radius_m: number;
  direction: LoiterDirection;
  exit_xtrack: boolean;
};

export type NavLoiterTime = {
  position: GeoPoint3d;
  time_s: number;
  direction: LoiterDirection;
  exit_xtrack: boolean;
};

export type NavLoiterToAlt = {
  position: GeoPoint3d;
  radius_m: number;
  direction: LoiterDirection;
  exit_xtrack: boolean;
};

export type NavContinueAndChangeAlt = {
  position: GeoPoint3d;
  action: AltChangeAction;
};

export type NavDelay = {
  seconds: number;
  hour_utc: number;
  min_utc: number;
  sec_utc: number;
};

export type NavGuidedEnable = {
  enabled: boolean;
};

export type NavAltitudeWait = {
  altitude_m: number;
  descent_rate_mps: number;
  wiggle_time_s: number;
};

export type NavVtolTakeoff = {
  position: GeoPoint3d;
};

export type NavVtolLand = {
  position: GeoPoint3d;
  options: number;
};

export type NavPayloadPlace = {
  position: GeoPoint3d;
  max_descent_m: number;
};

export type NavSetYawSpeed = {
  angle_deg: number;
  speed_mps: number;
  relative: boolean;
};

export type NavScriptTime = {
  command: number;
  timeout_s: number;
  arg1: number;
  arg2: number;
  arg3: number;
  arg4: number;
};

export type NavAttitudeTime = {
  time_s: number;
  roll_deg: number;
  pitch_deg: number;
  yaw_deg: number;
  climb_rate_mps: number;
};

// Externally-tagged enum generated by macro (no rename_all).
// Unit variant serializes as a string, data variants as { VariantName: data }.
export type NavCommand =
  | { Waypoint: NavWaypoint }
  | { SplineWaypoint: NavSplineWaypoint }
  | { ArcWaypoint: NavArcWaypoint }
  | { Takeoff: NavTakeoff }
  | { Land: NavLand }
  | { LoiterUnlimited: NavLoiterUnlimited }
  | { LoiterTurns: NavLoiterTurns }
  | { LoiterTime: NavLoiterTime }
  | { LoiterToAlt: NavLoiterToAlt }
  | { ContinueAndChangeAlt: NavContinueAndChangeAlt }
  | { Delay: NavDelay }
  | { GuidedEnable: NavGuidedEnable }
  | { AltitudeWait: NavAltitudeWait }
  | { VtolTakeoff: NavVtolTakeoff }
  | { VtolLand: NavVtolLand }
  | { PayloadPlace: NavPayloadPlace }
  | { SetYawSpeed: NavSetYawSpeed }
  | { ScriptTime: NavScriptTime }
  | { AttitudeTime: NavAttitudeTime }
  | "ReturnToLaunch";

// ---------------------------------------------------------------------------
// Do command structs
// ---------------------------------------------------------------------------

export type DoJump = { target_index: number; repeat_count: number };
export type DoJumpTag = { tag: number; repeat_count: number };
export type DoTag = { tag: number };
export type DoPauseContinue = { pause: boolean };
export type DoChangeSpeed = { speed_type: SpeedType; speed_mps: number; throttle_pct: number };
export type DoSetReverse = { reverse: boolean };
export type DoSetHome = { position: GeoPoint3d; use_current: boolean };
export type DoLandStart = { position: GeoPoint3d };
export type DoReturnPathStart = { position: GeoPoint3d };
export type DoGoAround = { position: GeoPoint3d };
export type DoSetRoiLocation = { position: GeoPoint3d };
export type DoSetRoi = { mode: number; position: GeoPoint3d };
export type DoMountControl = { pitch_deg: number; roll_deg: number; yaw_deg: number };
export type DoGimbalManagerPitchYaw = {
  pitch_deg: number;
  yaw_deg: number;
  pitch_rate_dps: number;
  yaw_rate_dps: number;
  flags: number;
  gimbal_id: number;
};
export type DoCamTriggerDistance = { meters: number; trigger_now: boolean };
export type DoImageStartCapture = {
  instance: number;
  interval_s: number;
  total_images: number;
  start_number: number;
};
export type DoImageStopCapture = { instance: number };
export type DoVideoStartCapture = { stream_id: number };
export type DoVideoStopCapture = { stream_id: number };
export type DoSetCameraZoom = { zoom_type: number; zoom_value: number };
export type DoSetCameraFocus = { focus_type: number; focus_value: number };
export type DoSetCameraSource = { instance: number; primary: number; secondary: number };
export type DoDigicamConfigure = {
  shooting_mode: number;
  shutter_speed: number;
  aperture: number;
  iso: number;
  exposure_type: number;
  cmd_id: number;
  cutoff_time: number;
};
export type DoDigicamControl = {
  session: number;
  zoom_pos: number;
  zoom_step: number;
  focus_lock: number;
  shooting_cmd: number;
  cmd_id: number;
};
export type DoSetServo = { channel: number; pwm: number };
export type DoSetRelay = { number: number; state: boolean };
export type DoRepeatServo = { channel: number; pwm: number; count: number; cycle_time_s: number };
export type DoRepeatRelay = { number: number; count: number; cycle_time_s: number };
export type DoFenceEnable = { action: FenceAction };
export type DoParachute = { action: ParachuteAction };
export type DoGripper = { number: number; action: GripperAction };
export type DoSprayer = { enabled: boolean };
export type DoWinch = {
  number: number;
  action: WinchAction;
  release_length_m: number;
  release_rate_mps: number;
};
export type DoEngineControl = {
  start: boolean;
  cold_start: boolean;
  height_delay_m: number;
  allow_disarmed: boolean;
};
export type DoInvertedFlight = { inverted: boolean };
export type DoAutotuneEnable = { enabled: boolean };
export type DoVtolTransition = { target_state: number };
export type DoGuidedLimits = {
  max_time_s: number;
  min_alt_m: number;
  max_alt_m: number;
  max_horiz_m: number;
};
export type DoSetResumeRepeatDist = { distance_m: number };
export type DoAuxFunction = { function: number; switch_pos: number };
export type DoSendScriptMessage = { id: number; p1: number; p2: number; p3: number };

// Externally-tagged enum generated by macro (no rename_all).
// Unit variant serializes as a string, data variants as { VariantName: data }.
export type DoCommand =
  | { Jump: DoJump }
  | { JumpTag: DoJumpTag }
  | { Tag: DoTag }
  | { PauseContinue: DoPauseContinue }
  | { ChangeSpeed: DoChangeSpeed }
  | { SetReverse: DoSetReverse }
  | { SetHome: DoSetHome }
  | { LandStart: DoLandStart }
  | { ReturnPathStart: DoReturnPathStart }
  | { GoAround: DoGoAround }
  | { SetRoiLocation: DoSetRoiLocation }
  | { SetRoi: DoSetRoi }
  | { MountControl: DoMountControl }
  | { GimbalManagerPitchYaw: DoGimbalManagerPitchYaw }
  | { CamTriggerDistance: DoCamTriggerDistance }
  | { ImageStartCapture: DoImageStartCapture }
  | { ImageStopCapture: DoImageStopCapture }
  | { VideoStartCapture: DoVideoStartCapture }
  | { VideoStopCapture: DoVideoStopCapture }
  | { SetCameraZoom: DoSetCameraZoom }
  | { SetCameraFocus: DoSetCameraFocus }
  | { SetCameraSource: DoSetCameraSource }
  | { DigicamConfigure: DoDigicamConfigure }
  | { DigicamControl: DoDigicamControl }
  | { SetServo: DoSetServo }
  | { SetRelay: DoSetRelay }
  | { RepeatServo: DoRepeatServo }
  | { RepeatRelay: DoRepeatRelay }
  | { FenceEnable: DoFenceEnable }
  | { Parachute: DoParachute }
  | { Gripper: DoGripper }
  | { Sprayer: DoSprayer }
  | { Winch: DoWinch }
  | { EngineControl: DoEngineControl }
  | { InvertedFlight: DoInvertedFlight }
  | { AutotuneEnable: DoAutotuneEnable }
  | { VtolTransition: DoVtolTransition }
  | { GuidedLimits: DoGuidedLimits }
  | { SetResumeRepeatDist: DoSetResumeRepeatDist }
  | { AuxFunction: DoAuxFunction }
  | { SendScriptMessage: DoSendScriptMessage }
  | "SetRoiNone";

// ---------------------------------------------------------------------------
// Condition command structs
// ---------------------------------------------------------------------------

export type CondDelay = { delay_s: number };
export type CondDistance = { distance_m: number };
export type CondYaw = {
  angle_deg: number;
  turn_rate_dps: number;
  direction: YawDirection;
  relative: boolean;
};

export type ConditionCommand =
  | { Delay: CondDelay }
  | { Distance: CondDistance }
  | { Yaw: CondYaw };

// ---------------------------------------------------------------------------
// Top-level MissionCommand
// ---------------------------------------------------------------------------

export type MissionCommand =
  | { Nav: NavCommand }
  | { Do: DoCommand }
  | { Condition: ConditionCommand }
  | { Other: RawMissionCommand };

// ---------------------------------------------------------------------------
// Mission plan types
// ---------------------------------------------------------------------------

export type MissionItem = {
  command: MissionCommand;
  current: boolean;
  autocontinue: boolean;
};

export type MissionPlan = {
  items: MissionItem[];
};

export type HomePosition = {
  latitude_deg: number;
  longitude_deg: number;
  altitude_m: number;
};

// ---------------------------------------------------------------------------
// Fence types
// ---------------------------------------------------------------------------

export type FenceInclusionPolygon = {
  vertices: GeoPoint2d[];
  inclusion_group: number;
};

export type FenceExclusionPolygon = {
  vertices: GeoPoint2d[];
};

export type FenceInclusionCircle = {
  center: GeoPoint2d;
  radius_m: number;
  inclusion_group: number;
};

export type FenceExclusionCircle = {
  center: GeoPoint2d;
  radius_m: number;
};

// FenceRegion uses #[serde(rename_all = "snake_case")] in Rust.
export type FenceRegion =
  | { inclusion_polygon: FenceInclusionPolygon }
  | { exclusion_polygon: FenceExclusionPolygon }
  | { inclusion_circle: FenceInclusionCircle }
  | { exclusion_circle: FenceExclusionCircle };

export type FencePlan = {
  return_point: GeoPoint2d | null;
  regions: FenceRegion[];
};

// ---------------------------------------------------------------------------
// Rally types
// ---------------------------------------------------------------------------

export type RallyPlan = {
  points: GeoPoint3d[];
};

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/** Extract the nav command variant from a MissionCommand, or null if not Nav. */
function navVariant(cmd: MissionCommand): NavCommand | null {
  if ("Nav" in cmd) return cmd.Nav;
  return null;
}

/** Extract the do command variant from a MissionCommand, or null if not Do. */
function doVariant(cmd: MissionCommand): DoCommand | null {
  if ("Do" in cmd) return cmd.Do;
  return null;
}

// Nav variants that carry a `position` field.
const NAV_POSITION_KEYS = [
  "Waypoint",
  "SplineWaypoint",
  "ArcWaypoint",
  "Takeoff",
  "Land",
  "LoiterUnlimited",
  "LoiterTurns",
  "LoiterTime",
  "LoiterToAlt",
  "ContinueAndChangeAlt",
  "VtolTakeoff",
  "VtolLand",
  "PayloadPlace",
] as const;

// Do variants that carry a `position` field.
const DO_POSITION_KEYS = [
  "SetHome",
  "LandStart",
  "ReturnPathStart",
  "GoAround",
  "SetRoiLocation",
  "SetRoi",
] as const;

/** Extract position from any command that has one. */
export function commandPosition(cmd: MissionCommand): GeoPoint3d | null {
  const nav = navVariant(cmd);
  if (nav !== null && typeof nav === "object") {
    for (const key of NAV_POSITION_KEYS) {
      if (key in nav) {
        return (nav as Record<string, { position: GeoPoint3d }>)[key].position;
      }
    }
  }

  const d = doVariant(cmd);
  if (d !== null && typeof d === "object") {
    for (const key of DO_POSITION_KEYS) {
      if (key in d) {
        return (d as Record<string, { position: GeoPoint3d }>)[key].position;
      }
    }
  }

  return null;
}

/** Check if a command has a position field. */
export function commandHasPosition(cmd: MissionCommand): boolean {
  return commandPosition(cmd) !== null;
}

/** Get the top-level category of a command. */
export function commandCategory(
  cmd: MissionCommand,
): "nav" | "do" | "condition" | "other" {
  if ("Nav" in cmd) return "nav";
  if ("Do" in cmd) return "do";
  if ("Condition" in cmd) return "condition";
  return "other";
}

/** Convert a PascalCase variant key to a human-readable display name. */
function pascalToDisplay(name: string): string {
  // Insert spaces before uppercase letters that follow lowercase letters or
  // before sequences of uppercase followed by lowercase (e.g., "ROILocation" -> "ROI Location").
  return name
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2");
}

/** Human-readable display name for a mission command. */
export function commandDisplayName(cmd: MissionCommand): string {
  if ("Nav" in cmd) {
    const nav = cmd.Nav;
    if (typeof nav === "string") return pascalToDisplay(nav);
    const key = Object.keys(nav)[0];
    return pascalToDisplay(key);
  }
  if ("Do" in cmd) {
    const d = cmd.Do;
    if (typeof d === "string") return pascalToDisplay(d);
    const key = Object.keys(d)[0];
    return pascalToDisplay(key);
  }
  if ("Condition" in cmd) {
    const c = cmd.Condition;
    const key = Object.keys(c)[0];
    return pascalToDisplay(key);
  }
  if ("Other" in cmd) {
    return `Command #${cmd.Other.command}`;
  }
  return "Unknown";
}

/** Extract lat/lon from a GeoPoint3d, ignoring altitude. */
export function geoPoint3dLatLon(
  pt: GeoPoint3d,
): { latitude_deg: number; longitude_deg: number } {
  if ("Msl" in pt) {
    return { latitude_deg: pt.Msl.latitude_deg, longitude_deg: pt.Msl.longitude_deg };
  }
  if ("RelHome" in pt) {
    return {
      latitude_deg: pt.RelHome.latitude_deg,
      longitude_deg: pt.RelHome.longitude_deg,
    };
  }
  // Terrain
  const t = (pt as { Terrain: GeoPoint3dTerrain }).Terrain;
  return { latitude_deg: t.latitude_deg, longitude_deg: t.longitude_deg };
}

/** Extract the altitude value and frame name from a GeoPoint3d. */
export function geoPoint3dAltitude(
  pt: GeoPoint3d,
): { value: number; frame: "msl" | "rel_home" | "terrain" } {
  if ("Msl" in pt) return { value: pt.Msl.altitude_msl_m, frame: "msl" };
  if ("RelHome" in pt) return { value: pt.RelHome.relative_alt_m, frame: "rel_home" };
  const t = (pt as { Terrain: GeoPoint3dTerrain }).Terrain;
  return { value: t.altitude_terrain_m, frame: "terrain" };
}

/** Create a new GeoPoint3d with updated lat/lon, preserving the altitude frame. */
export function withGeoPoint3dPosition(
  pt: GeoPoint3d,
  lat: number,
  lon: number,
): GeoPoint3d {
  if ("Msl" in pt) {
    return { Msl: { latitude_deg: lat, longitude_deg: lon, altitude_msl_m: pt.Msl.altitude_msl_m } };
  }
  if ("RelHome" in pt) {
    return {
      RelHome: { latitude_deg: lat, longitude_deg: lon, relative_alt_m: pt.RelHome.relative_alt_m },
    };
  }
  const t = (pt as { Terrain: GeoPoint3dTerrain }).Terrain;
  return {
    Terrain: { latitude_deg: lat, longitude_deg: lon, altitude_terrain_m: t.altitude_terrain_m },
  };
}

/** Create a new GeoPoint3d with updated altitude, preserving the frame and lat/lon. */
export function withGeoPoint3dAltitude(pt: GeoPoint3d, alt: number): GeoPoint3d {
  if ("Msl" in pt) {
    return {
      Msl: {
        latitude_deg: pt.Msl.latitude_deg,
        longitude_deg: pt.Msl.longitude_deg,
        altitude_msl_m: alt,
      },
    };
  }
  if ("RelHome" in pt) {
    return {
      RelHome: {
        latitude_deg: pt.RelHome.latitude_deg,
        longitude_deg: pt.RelHome.longitude_deg,
        relative_alt_m: alt,
      },
    };
  }
  const t = (pt as { Terrain: GeoPoint3dTerrain }).Terrain;
  return {
    Terrain: {
      latitude_deg: t.latitude_deg,
      longitude_deg: t.longitude_deg,
      altitude_terrain_m: alt,
    },
  };
}

/** Create a default GeoPoint3d in the RelHome frame. */
export function defaultGeoPoint3d(
  lat: number,
  lon: number,
  alt: number,
): GeoPoint3d {
  return { RelHome: { latitude_deg: lat, longitude_deg: lon, relative_alt_m: alt } };
}
