export const setupWorkspaceTestIds = {
  root: "setup-workspace",
  state: "setup-workspace-state",
  scope: "setup-workspace-scope",
  metadata: "setup-workspace-metadata",
  progress: "setup-workspace-progress",
  notice: "setup-workspace-notice",
  selectedSection: "setup-workspace-selected-section",
  checkpoint: "setup-workspace-checkpoint",
  notices: "setup-workspace-status-notices",
  statusNoticePrefix: "setup-workspace-status-notice",
  navPrefix: "setup-workspace-nav",
  sectionStatusPrefix: "setup-workspace-section-status",
  sectionConfidencePrefix: "setup-workspace-section-confidence",
  sectionGatePrefix: "setup-workspace-section-gate",
  overviewCardPrefix: "setup-workspace-overview-card",
  detail: "setup-workspace-detail",
  detailStatus: "setup-workspace-detail-status",
  detailRecovery: "setup-workspace-detail-recovery",
  fullParameters: "setup-workspace-full-parameters",
} as const;
