export const parameterWorkspaceTestIds = {
  root: "parameter-workspace",
  state: "parameter-workspace-state",
  readiness: "parameter-domain-readiness",
  scope: "parameter-domain-scope",
  progress: "parameter-domain-progress",
  metadata: "parameter-domain-metadata",
  notice: "parameter-domain-notice",
  empty: "parameter-workspace-empty",
  pendingCount: "parameter-workspace-pending-count",
  pendingHint: "parameter-workspace-pending-hint",
  sectionPrefix: "parameter-workspace-section",
  itemPrefix: "parameter-workspace-item",
  diffPrefix: "parameter-workspace-diff",
  inputPrefix: "parameter-workspace-input",
  stageButtonPrefix: "parameter-workspace-stage-btn",
  discardButtonPrefix: "parameter-workspace-discard-btn",
  rebootBadgePrefix: "parameter-workspace-reboot-badge",
} as const;
