use std::{env, error::Error, fs, path::PathBuf, process};

use ironwing_core::{
    event_names,
    ipc::{self, calibration, guided, logs},
    live_runtime, telemetry, transport,
};
use ironwing_firmware::{DfuRecoveryResult, types as firmware};
use specta::{Type, Types, datatype::DataType};
use specta_typescript::Typescript;

const HEADER: &str = "// @generated by `cargo run -p ironwing-contract-export --`\n// Do not edit this file by hand.\n";

const COMMAND_NAMES: &[&str] = &[
    "ack_session_snapshot",
    "arm_vehicle",
    "available_transports",
    "bt_get_bonded_devices",
    "bt_request_permissions",
    "bt_scan_ble",
    "bt_stop_scan_ble",
    "calibrate_accel",
    "calibrate_compass_accept",
    "calibrate_compass_cancel",
    "calibrate_compass_start",
    "calibrate_gyro",
    "connect_link",
    "disconnect_link",
    "disarm_vehicle",
    "fence_clear",
    "fence_download",
    "fence_upload",
    "firmware_bootloader_installation",
    "firmware_detect_bootloader_board",
    "firmware_install_update",
    "firmware_install_update_preflight",
    "firmware_install_update_readiness",
    "firmware_list_dfu_devices",
    "firmware_reboot_to_bootloader",
    "firmware_session_cancel",
    "firmware_session_clear_completed",
    "firmware_session_status",
    "get_available_message_rates",
    "get_available_modes",
    "list_serial_port_inventory",
    "log_chart_series_query",
    "log_close",
    "log_export",
    "log_export_csv",
    "log_format_adapters",
    "log_get_flight_path",
    "log_get_flight_summary",
    "log_get_summary",
    "log_get_telemetry_track",
    "log_library_cancel",
    "log_library_list",
    "log_library_register",
    "log_library_register_open_file",
    "log_library_reindex",
    "log_library_relink",
    "log_library_remove",
    "log_open",
    "log_query",
    "log_raw_messages_query",
    "mission_cancel",
    "mission_clear",
    "mission_download",
    "mission_set_current",
    "mission_upload",
    "mission_validate",
    "motor_test",
    "open_session_snapshot",
    "param_cancel",
    "param_download_all",
    "param_format_file",
    "param_write",
    "param_write_batch",
    "playback_pause",
    "playback_play",
    "playback_seek",
    "playback_set_speed",
    "playback_stop",
    "rally_clear",
    "rally_download",
    "rally_upload",
    "rc_override",
    "reboot_vehicle",
    "recording_settings_read",
    "recording_settings_write",
    "recording_start",
    "recording_status",
    "recording_stop",
    "request_prearm_checks",
    "request_web_serial_port",
    "set_flight_mode",
    "set_message_rate",
    "set_servo",
    "set_telemetry_rate",
    "start_guided_session",
    "stop_guided_session",
    "update_guided_session",
    "vehicle_takeoff",
];

fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let output_dir = generated_dir()?;
    let files = generated_files()?;

    if check {
        let mut changed = Vec::new();
        for (name, content) in &files {
            let path = output_dir.join(name);
            let current = fs::read_to_string(&path).unwrap_or_default();
            if current != *content {
                changed.push(path);
            }
        }

        if changed.is_empty() {
            println!("generated contract files are up to date");
            return Ok(());
        }

        eprintln!(
            "generated contract files are out of date; run `cargo run -p ironwing-contract-export --`"
        );
        for path in changed {
            eprintln!("  differs: {}", path.display());
        }
        process::exit(1);
    }

    fs::create_dir_all(&output_dir)?;
    for (name, content) in files {
        fs::write(output_dir.join(name), content)?;
    }
    println!("wrote generated contract files to {}", output_dir.display());

    Ok(())
}

fn generated_dir() -> Result<PathBuf, Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(|path| path.parent())
        .ok_or("failed to resolve workspace root from exporter manifest directory")?;
    Ok(workspace_root.join("src/lib/generated"))
}

fn generated_files() -> Result<Vec<(&'static str, String)>, Box<dyn Error>> {
    Ok(vec![
        ("mavkit.ts", generated_mavkit()?),
        ("ironwing.ts", generated_ironwing()?),
        ("events.ts", generated_events()?),
        ("commands.ts", generated_commands()?),
        ("index.ts", generated_index()),
    ])
}

fn generated_mavkit() -> Result<String, Box<dyn Error>> {
    let mut types = Types::default();

    types
        .register_mut::<mavkit::MissionPlan>()
        .register_mut::<mavkit::MissionItem>()
        .register_mut::<mavkit::MissionCommand>()
        .register_mut::<mavkit::RawMissionCommand>()
        .register_mut::<mavkit::mission::commands::MissionFrame>()
        .register_mut::<mavkit::MissionType>()
        .register_mut::<mavkit::HomePosition>()
        .register_mut::<mavkit::mission::MissionState>()
        .register_mut::<mavkit::MissionIssue>()
        .register_mut::<mavkit::IssueSeverity>()
        .register_mut::<mavkit::TransferDirection>()
        .register_mut::<mavkit::TransferPhase>()
        .register_mut::<mavkit::TransferProgress>()
        .register_mut::<mavkit::TransferError>()
        .register_mut::<mavkit::RetryPolicy>()
        .register_mut::<mavkit::Param>()
        .register_mut::<mavkit::ParamStore>()
        .register_mut::<mavkit::ParamType>()
        .register_mut::<mavkit::ParamState>()
        .register_mut::<mavkit::ParamWriteResult>()
        .register_mut::<mavkit::ParamOperationKind>()
        .register_mut::<mavkit::ParamOperationProgress>()
        .register_mut::<mavkit::FencePlan>()
        .register_mut::<mavkit::FenceState>()
        .register_mut::<mavkit::FenceRegion>()
        .register_mut::<mavkit::FenceInclusionPolygon>()
        .register_mut::<mavkit::FenceExclusionPolygon>()
        .register_mut::<mavkit::FenceInclusionCircle>()
        .register_mut::<mavkit::FenceExclusionCircle>()
        .register_mut::<mavkit::RallyPlan>()
        .register_mut::<mavkit::RallyState>()
        .register_mut::<mavkit::GeoPoint2d>()
        .register_mut::<mavkit::GeoPoint3d>()
        .register_mut::<mavkit::GeoPoint3dMsl>()
        .register_mut::<mavkit::GeoPoint3dRelHome>()
        .register_mut::<mavkit::GeoPoint3dTerrain>()
        .register_mut::<mavkit::SensorHealthState>()
        .register_mut::<mavkit::SensorHealthSummary>()
        .register_mut::<mavkit::SupportState>()
        .register_mut::<mavkit::SyncState>()
        .register_mut::<mavkit::MissionOperationKind>()
        .register_mut::<mavkit::MissionOperationProgress>()
        .register_mut::<mavkit::StoredPlanOperationKind>()
        .register_mut::<mavkit::OperationConflict>()
        .register_mut::<mavkit::SystemStatus>()
        .register_mut::<mavkit::VehicleType>()
        .register_mut::<mavkit::AutopilotType>()
        .register_mut::<mavkit::MavSeverity>()
        .register_mut::<mavkit::GpsFixType>()
        .register_mut::<mavkit::FlightMode>()
        .register_mut::<mavkit::GlobalPosition>()
        .register_mut::<mavkit::EulerAttitude>()
        .register_mut::<mavkit::CellVoltages>()
        .register_mut::<mavkit::GpsQuality>()
        .register_mut::<mavkit::WaypointProgress>()
        .register_mut::<mavkit::GuidanceState>()
        .register_mut::<mavkit::TerrainClearance>()
        .register_mut::<mavkit::StatusTextEvent>()
        .register_mut::<mavkit::TelemetryMessageKind>()
        .register_mut::<mavkit::VehicleTimestamp>()
        .register_mut::<mavkit::AltChangeAction>()
        .register_mut::<mavkit::FenceAction>()
        .register_mut::<mavkit::GripperAction>()
        .register_mut::<mavkit::LoiterDirection>()
        .register_mut::<mavkit::ParachuteAction>()
        .register_mut::<mavkit::SpeedType>()
        .register_mut::<mavkit::WinchAction>()
        .register_mut::<mavkit::YawDirection>()
        .register_mut::<mavkit::NavCommand>()
        .register_mut::<mavkit::DoCommand>()
        .register_mut::<mavkit::ConditionCommand>();

    let semantic = semantic_config();
    let semantic_types = semantic.apply_types(&types);
    let body = Typescript::default().export(semantic_types.as_ref(), specta_serde::Format)?;
    Ok(with_header(body))
}

fn generated_ironwing() -> Result<String, Box<dyn Error>> {
    let mut types = Types::default();

    types
        .register_mut::<transport::TransportDescriptor>()
        .register_mut::<transport::UdpValidation>()
        .register_mut::<transport::TcpValidation>()
        .register_mut::<transport::SerialValidation>()
        .register_mut::<transport::AddressValidation>()
        .register_mut::<transport::UrlValidation>()
        .register_mut::<transport::WebSerialValidation>()
        .register_mut::<transport::WebBluetoothValidation>()
        .register_mut::<transport::DemoValidation>()
        .register_mut::<transport::BluetoothProfile>()
        .register_mut::<live_runtime::Capability>()
        .register_mut::<live_runtime::RuntimeCapabilities>()
        .register_mut::<telemetry::MessageRateInfo>()
        .register_mut::<telemetry::MessageIntervalRequest>()
        .register_mut::<ipc::SourceKind>()
        .register_mut::<ipc::SessionEnvelope>()
        .register_mut::<ipc::OperationId>()
        .register_mut::<ipc::ReasonKind>()
        .register_mut::<ipc::Reason>()
        .register_mut::<ipc::OperationFailure>()
        .register_mut::<ipc::DomainProvenance>()
        .register_mut::<ipc::domain::DomainValue<ipc::telemetry::TelemetryState>>()
        .register_mut::<ipc::AnalyticsProperty>()
        .register_mut::<logs::LogFormat>()
        .register_mut::<logs::LogFormatAdapter>()
        .register_mut::<logs::ReferencedFileFingerprint>()
        .register_mut::<logs::ReferencedFileStatus>()
        .register_mut::<logs::ReferencedLogFile>()
        .register_mut::<logs::LogDiagnosticSeverity>()
        .register_mut::<logs::LogDiagnosticSource>()
        .register_mut::<ipc::LogDiagnostic>()
        .register_mut::<logs::LogMetadata>()
        .register_mut::<logs::LogIndexReference>()
        .register_mut::<logs::LogLibraryEntryStatus>()
        .register_mut::<logs::LogLibraryEntry>()
        .register_mut::<logs::LogLibraryStorageLocation>()
        .register_mut::<logs::LogLibraryCatalog>()
        .register_mut::<logs::LogCatalogMigrationError>()
        .register_mut::<ipc::LogOperationPhase>()
        .register_mut::<ipc::LogOperationProgress>()
        .register_mut::<ipc::ReplayStatus>()
        .register_mut::<logs::RawMessageFieldFilter>()
        .register_mut::<logs::RawMessageQuery>()
        .register_mut::<logs::RawMessageRecord>()
        .register_mut::<logs::RawMessagePage>()
        .register_mut::<logs::ChartSeriesSelector>()
        .register_mut::<logs::ChartSeriesRequest>()
        .register_mut::<logs::ChartPoint>()
        .register_mut::<logs::ChartSeries>()
        .register_mut::<logs::ChartSeriesPage>()
        .register_mut::<logs::LogExportFormat>()
        .register_mut::<logs::LogExportRequest>()
        .register_mut::<logs::LogExportResult>()
        .register_mut::<ipc::RecordingMode>()
        .register_mut::<ipc::RecordingSettings>()
        .register_mut::<ipc::RecordingStatus>()
        .register_mut::<ipc::RecordingStartRequest>()
        .register_mut::<ipc::RecordingSettingsResult>()
        .register_mut::<logs::RecordingFailure>()
        .register_mut::<ipc::MissionDownload>()
        .register_mut::<ipc::RcOverrideChannelValueWire>()
        .register_mut::<ipc::RcOverrideChannelWire>()
        .register_mut::<calibration::CalibrationLifecycle>()
        .register_mut::<calibration::CalibrationStep>()
        .register_mut::<calibration::CalibrationState>()
        .register_mut::<ipc::PlaybackSnapshot>()
        .register_mut::<ipc::playback::PlaybackSeekResult>()
        .register_mut::<ipc::playback::PlaybackState>()
        .register_mut::<ipc::telemetry::TelemetryFlight>()
        .register_mut::<ipc::telemetry::TelemetryNavigation>()
        .register_mut::<ipc::telemetry::TelemetryAttitude>()
        .register_mut::<ipc::telemetry::TelemetryPower>()
        .register_mut::<ipc::telemetry::TelemetryGps>()
        .register_mut::<ipc::telemetry::TelemetryTerrain>()
        .register_mut::<ipc::telemetry::TelemetryRadio>()
        .register_mut::<ipc::telemetry::TelemetryState>()
        .register_mut::<ipc::support::SupportState>()
        .register_mut::<ipc::StatusTextEntry>()
        .register_mut::<ipc::status_text::StatusTextState>()
        .register_mut::<guided::GuidedStatus>()
        .register_mut::<guided::GuidedBlockingReason>()
        .register_mut::<ipc::GuidedTerminationReason>()
        .register_mut::<ipc::GuidedFatalityScope>()
        .register_mut::<guided::GuidedSessionKind>()
        .register_mut::<ipc::GuidedSession>()
        .register_mut::<guided::GuidedAction>()
        .register_mut::<guided::GuidedActions>()
        .register_mut::<guided::GuidedTermination>()
        .register_mut::<guided::GuidedLastCommand>()
        .register_mut::<guided::GuidedState>()
        .register_mut::<ipc::StartGuidedSessionRequest>()
        .register_mut::<ipc::UpdateGuidedSessionRequest>()
        .register_mut::<ipc::guided::GuidedFailureDetail>()
        .register_mut::<ipc::GuidedFailure>()
        .register_mut::<ipc::GuidedCommandResult>()
        .register_mut::<ipc::SessionStatus>()
        .register_mut::<ipc::SessionConnection>()
        .register_mut::<ipc::VehicleState>()
        .register_mut::<ipc::SessionSnapshot>()
        .register_mut::<ipc::OpenSessionSnapshot>()
        .register_mut::<ipc::AckSessionSnapshotResult>()
        .register_mut::<firmware::FirmwareSessionStatus>()
        .register_mut::<firmware::FirmwareSessionPath>()
        .register_mut::<firmware::SerialFlashPhase>()
        .register_mut::<firmware::SerialFlashOutcome>()
        .register_mut::<firmware::DfuRecoveryPhase>()
        .register_mut::<firmware::DfuRecoveryOutcome>()
        .register_mut::<DfuRecoveryResult>()
        .register_mut::<firmware::FirmwareOutcome>()
        .register_mut::<firmware::FirmwareSource>()
        .register_mut::<firmware::SerialBoardIdentity>()
        .register_mut::<firmware::DfuRecoveryIdentity>()
        .register_mut::<firmware::ActionRequired>()
        .register_mut::<firmware::FirmwareProgress>()
        .register_mut::<firmware::PortInfo>()
        .register_mut::<firmware::InventoryResult>()
        .register_mut::<firmware::DfuDeviceInfo>()
        .register_mut::<firmware::DfuScanResult>()
        .register_mut::<firmware::CatalogEntry>()
        .register_mut::<firmware::CatalogTargetSummary>()
        .register_mut::<firmware::SerialPreflightInfo>()
        .register_mut::<firmware::SerialFlashSource>()
        .register_mut::<firmware::SerialFlashOptions>()
        .register_mut::<firmware::SerialReadinessRequest>()
        .register_mut::<firmware::SerialReadiness>()
        .register_mut::<firmware::SerialReadinessResponse>()
        .register_mut::<firmware::FirmwareInstallBootloaderStatus>()
        .register_mut::<firmware::SerialReadinessBlockedReason>()
        .register_mut::<firmware::FirmwareBootloaderBoardInfo>()
        .register_mut::<firmware::FirmwareRebootToBootloaderResult>()
        .register_mut::<firmware::DfuRecoverySource>()
        .register_mut::<firmware::SerialFlowResult>()
        .register_mut::<firmware::FirmwareError>();

    let semantic = semantic_config();
    let semantic_types = semantic.apply_types(&types);
    let mut body =
        Typescript::default().export(semantic_types.as_ref(), specta_serde::PhasesFormat)?;
    body.push('\n');
    body.push_str(&operation_ids_ts()?);
    body.push('\n');
    body.push_str(&telemetry_constants_ts()?);

    Ok(with_header(body))
}

fn telemetry_constants_ts() -> Result<String, Box<dyn Error>> {
    let mut body = String::new();
    body.push_str("export const MESSAGE_RATE_CATALOG = ");
    body.push_str(&serde_json::to_string_pretty(
        telemetry::AVAILABLE_MESSAGE_RATES,
    )?);
    body.push_str(" as const satisfies readonly MessageRateInfo[];\n\n");
    body.push_str("export const MESSAGE_RATE_LIMITS = ");
    body.push_str(&serde_json::to_string_pretty(&serde_json::json!({
        "min": telemetry::MIN_MESSAGE_RATE_HZ,
        "max": telemetry::MAX_MESSAGE_RATE_HZ,
    }))?);
    body.push_str(" as const;\n\n");
    body.push_str("export const TELEMETRY_RATE_LIMITS = ");
    body.push_str(&serde_json::to_string_pretty(&serde_json::json!({
        "min": telemetry::MIN_TELEMETRY_RATE_HZ,
        "max": telemetry::MAX_TELEMETRY_RATE_HZ,
    }))?);
    body.push_str(" as const;\n");

    Ok(body)
}

fn generated_events() -> Result<String, Box<dyn Error>> {
    let events = [
        ("SESSION_STATE", event_names::SESSION_STATE),
        ("TELEMETRY_STATE", event_names::TELEMETRY_STATE),
        ("MISSION_STATE", event_names::MISSION_STATE),
        ("MISSION_PROGRESS", event_names::MISSION_PROGRESS),
        ("PARAM_STORE", event_names::PARAM_STORE),
        ("PARAM_PROGRESS", event_names::PARAM_PROGRESS),
        ("SENSOR_HEALTH_STATE", event_names::SENSOR_HEALTH_STATE),
        ("CALIBRATION_STATE", event_names::CALIBRATION_STATE),
        ("COMPASS_CAL_PROGRESS", event_names::COMPASS_CAL_PROGRESS),
        ("COMPASS_CAL_REPORT", event_names::COMPASS_CAL_REPORT),
        ("STATUS_TEXT_STATE", event_names::STATUS_TEXT_STATE),
        ("SUPPORT_STATE", event_names::SUPPORT_STATE),
        ("GUIDED_STATE", event_names::GUIDED_STATE),
        ("PLAYBACK_STATE", event_names::PLAYBACK_STATE),
        ("LOG_PROGRESS", event_names::LOG_PROGRESS),
        ("FIRMWARE_PROGRESS", event_names::FIRMWARE_PROGRESS),
    ];

    let mut body = String::from("export const EVENT_NAMES = {\n");
    for (key, value) in events {
        body.push_str("  ");
        body.push_str(key);
        body.push_str(": ");
        body.push_str(&serde_json::to_string(value)?);
        body.push_str(",\n");
    }
    body.push_str("} as const;\n\n");
    body.push_str("export type EventName = (typeof EVENT_NAMES)[keyof typeof EVENT_NAMES];\n");

    Ok(with_header(body))
}

fn generated_commands() -> Result<String, Box<dyn Error>> {
    let mut body = String::from("export const INVOKE_COMMAND_NAMES = [\n");
    for name in COMMAND_NAMES {
        body.push_str("  ");
        body.push_str(&serde_json::to_string(name)?);
        body.push_str(",\n");
    }
    body.push_str("] as const;\n\n");
    body.push_str("export type InvokeCommandName = (typeof INVOKE_COMMAND_NAMES)[number];\n");

    Ok(with_header(body))
}

fn generated_index() -> String {
    with_header(
        "export * as MavkitContracts from \"./mavkit\";\nexport * as IronWingContracts from \"./ironwing\";\nexport * from \"./events\";\nexport * from \"./commands\";\n",
    )
}

fn operation_ids_ts() -> Result<String, Box<dyn Error>> {
    let mut body = String::from("export const OPERATION_IDS = [\n");
    for operation_id in ipc::OperationId::ALL {
        body.push_str("  ");
        body.push_str(&serde_json::to_string(operation_id.as_str())?);
        body.push_str(",\n");
    }
    body.push_str("] as const;\n");
    Ok(body)
}

fn semantic_config() -> specta_typescript::semantic::Configuration {
    specta_typescript::semantic::Configuration::default()
        .enable_lossless_bigints()
        .define::<serde_json::Value>(|_| unknown_datatype(), None, None)
        .define::<serde_json::Number>(|_| number_datatype(), None, None)
}

fn unknown_datatype() -> DataType {
    specta_typescript::Unknown::<()>::definition(&mut Types::default())
}

fn number_datatype() -> DataType {
    specta_typescript::Number::<()>::definition(&mut Types::default())
}

fn with_header(body: impl AsRef<str>) -> String {
    let mut output = String::from(HEADER);
    output.push_str(&trim_trailing_line_whitespace(body.as_ref()));
    if !output.ends_with('\n') {
        output.push('\n');
    }
    output
}

fn trim_trailing_line_whitespace(value: &str) -> String {
    value
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
}
