export const parameterWorkspaceTestIds = {
    root: "parameter-workspace",
    state: "parameter-workspace-state",
    scope: "parameter-domain-scope",
    progress: "parameter-domain-progress",
    metadata: "parameter-domain-metadata",
    notice: "parameter-domain-notice",
    empty: "parameter-workspace-empty",
    pendingCount: "parameter-workspace-pending-count",
    pendingHint: "parameter-workspace-pending-hint",
    expertRoot: "parameter-expert-browser",
    expertSearch: "parameter-expert-search",
    expertSummary: "parameter-expert-summary",
    expertFilterPrefix: "parameter-expert-filter",
    expertMetadataFallback: "parameter-expert-metadata-fallback",
    expertNoMatches: "parameter-expert-no-matches",
    expertGroupPrefix: "parameter-expert-group",
    expertHiddenStaged: "parameter-expert-hidden-staged",
    itemPrefix: "parameter-workspace-item",
    diffPrefix: "parameter-workspace-diff",
    inputPrefix: "parameter-workspace-input",
    discardButtonPrefix: "parameter-workspace-discard-btn",
    rebootBadgePrefix: "parameter-workspace-reboot-badge",
    failurePrefix: "parameter-workspace-failure",
} as const;
