export const parameterWorkspaceTestIds = {
    root: "parameter-workspace",
    state: "parameter-workspace-state",
    scope: "parameter-domain-scope",
    progress: "parameter-domain-progress",
    metadata: "parameter-domain-metadata",
    notice: "parameter-domain-notice",
    empty: "parameter-workspace-empty",
    pendingCount: "parameter-workspace-pending-count",
    pendingHint: "parameter-workspace-pending-hint",
    catalogRoot: "parameter-catalog-browser",
    catalogSearch: "parameter-catalog-search",
    catalogSummary: "parameter-catalog-summary",
    catalogFilterPrefix: "parameter-catalog-filter",
    catalogMetadataFallback: "parameter-catalog-metadata-fallback",
    catalogNoMatches: "parameter-catalog-no-matches",
    catalogGroupPrefix: "parameter-catalog-group",
    catalogHiddenStaged: "parameter-catalog-hidden-staged",
    itemPrefix: "parameter-workspace-item",
    inputPrefix: "parameter-workspace-input",
    discardButtonPrefix: "parameter-workspace-discard-btn",
} as const;
